{{- if or (ne .Values.image.repository "ghcr.io/porter-dev/porter/hello-porter-job") (.Values.global) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "docker-template.fullname" . }}
automountServiceAccountToken: true
{{- end }}
